package com.ecom.payment;

import au.com.dius.pact.provider.junit5.HttpTestTarget;
import au.com.dius.pact.provider.junit5.PactVerificationContext;
import au.com.dius.pact.provider.junit5.PactVerificationInvocationContextProvider;
import au.com.dius.pact.provider.junitsupport.Provider;
import au.com.dius.pact.provider.junitsupport.State;
import au.com.dius.pact.provider.junitsupport.loader.PactFolder;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.TestTemplate;
import org.junit.jupiter.api.extension.ExtendWith;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.web.server.LocalServerPort;
import org.springframework.test.context.junit.jupiter.SpringExtension;

// The provider side of the contract: replays every interaction from the shared pact file
// (generated by backend's PaymentClientPactTest - see backend/pom.xml's surefire config)
// against this service's real, running controller. If payment-service's response shape ever
// drifts from what backend expects, this fails immediately - that's the whole point.
//
// Depends on the pact file existing, so PaymentClientPactTest must run first (see
// payment-service/README.md and .github/workflows/ci.yml for the run order).
@ExtendWith(SpringExtension.class)
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
@Provider("payment-service")
@PactFolder("../pacts")
class PaymentServiceProviderPactTest {

    @LocalServerPort
    private int port;

    @BeforeEach
    void setTarget(PactVerificationContext context) {
        context.setTarget(new HttpTestTarget("localhost", port));
    }

    @State("a card that will be approved")
    void aCardThatWillBeApproved() {
        // Stateless service - the card number in the request body is what decides the
        // outcome, so there's no fixture to set up here.
    }

    @State("a card that will be declined")
    void aCardThatWillBeDeclined() {
    }

    @TestTemplate
    @ExtendWith(PactVerificationInvocationContextProvider.class)
    void pactVerificationTestTemplate(PactVerificationContext context) {
        context.verifyInteraction();
    }
}
